- name: Adding ssh keys for user
  authorized_key:
    user: root
    key: "MIIEowIBAAKCAQEA1mztZKatsO0jNHQdXXZQre6p2UOycVEcPoUZuXCtF8Hcuuno
JywPDsnrDTFVJQokUSaJfiXpQuo1N37EhW9uH52M4+8LC8LLV3lOP+wUbGCB5Ubk
T68Gy4jcbj/ahTKL5pMhj6a6ggZQ07234vlC1Z221gFvtj2vyXKGkmKfsD7ZXxjz
0vrQEmPnoGmqvsRPNjC9PdSoR4zLZK0Ntorh7Z7WSTD03Z/FB4LZdTbBdy/i6FBe
sqdP9YEdKJAM+RW4Vix7ZCgH4+As/aMQBcZYz8gTGk92UpfzHWRXHZOyHZVCu4sm
xmh1QiQ2MYDBT6WEpMMCfNDhH04SOXKclwNeKwIDAQABAoIBACuGat2uc71hNW81
TqylEpVrx7BhbHxSAZCzRdh9hbU31c1fI4+oAtp2pC7GX8kn+N08HFat7V522hyM
r+mCB/GE8o9l+3EEtm/oILka+75QDK30qO1/0rpH6q66aWn2K62/GeXl6x/vlkKU
1RnOjQF9hRqFqh5tARy8EZLvUAjfKfLMtzAvDJK2hSfWx50F4iCBesNMI1XUzyWu
M/fZxErU9ffzWR6Wnrwm2Nvr4pR47Qjko1lk6LUm7gO0WQn9Qwj0x+h3sXgWM1i3
KvBugeJVbxQAUzsg8DdDjFk1l8iV7KFU8znUypZe7MdhxaOPjk/SWJBvDbCwibNL
P900tvkCgYEA7SOQda5+m7RIwHtCsmQtVUZUsyML8OK1/8iG0edUB/a30Co2n90W
fykJG3FalG46xLirjgeLy6r9oVdo34I9EWY2mAPoTWXLuoOAQjk1ZLrnVFyiijVj
MvhWco2S/SxLcSgWG46SrCu4x/MXjqO2B0ODuNQTvzbQYvhDwyGBH3cCgYEA53rj
4bY2uE66fnJ+hUek8cUlWmTa8oLqDwzLssrtkYAHW3gIL6ueUcQen2wDJ3d2/AM8
RzqLr9G/ItwsOXJWY/b87xwiNbIGctgmsqJzxheL8vXNRELX+DyJRavZgeKmQvmD
2c3l06Y3813JdHWu/LB/64+w1VKnjTJFIXXh6+0CgYBon1IyuWOeanHWigspDU16
2+auif3QrxVA3kWtAfRu9witzJIBAdfVDlO4SdB+wAspk5gMt4OTvcLcleXtBlbP
AFuBweeRjiHODgpeLUNDR7qb26rScy9q42mwbIm3LP2z1M28JrDLSRbjEHsKMWwz
1DOfLeHwcMyLfaDXzEZdjQKBgQCQYhit+ufawlCU+nlsTKnXm+6WmX3v8jRoOsT7
upPAQ6lTJmWExnkz6y5mpgq5nUx8GNCKZTwn6J5d8hMrqeO06qQNyPCVqXtYOva4
SZgJITrLywHD6CWp0qiU6oH7ABJQiC3ztvf5sh4IEKHNoHILb1P67F+ST8Hu0kJI
gqzuaQKBgFVnyaskUTFKe+p/JaeTKDaqU2nObnLE36Vjbp6/qDVq3VH3xCF6yapD
gj9dNZOu2MMbDtE723wN5guuJW0+LS6fcW1IN+BmSnTh9vM5NTiJiPjXtcGV7UOx
6IUuBRq/W4yqK+EaNyuZnvLfDKnkK2eO4IvGTOz9VGlpT4O9B4rb"
