- hosts: all
  name: Installing Packages
  become: true
  tasks:
    - name: Update index repository (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update index repository (CentOS)
      dnf:
        name: "*"
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Creating group [DevOps]
      group: 
        name: devops
        state: present

    - name: Creating a user [mandzukic]
      user: 
        name: mandzukic
        shell: /bin/bash
        home: /home/mandzukic
        group: devops
        append: true

    - name: Install and start Apache2 on Ubuntu webserver
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Ensure Apache2 is started and enabled (Ubuntu)
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_distribution == "Ubuntu"

    - name: Using Loop to install multiple packages
      apt:
        name: "{{ item }}"
        state: latest
      loop: 
        - git
        - wget
        - npm
        - tree
        - htop
      when: ansible_distribution == "Ubuntu"
