- hosts: all
  name: Setting up webserver
  become: true
  tasks:
    - name: Update index repository (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update index repository (CentOS)
      dnf:
        name: "*"
        state: latest
      when: ansible_distribution == "CentOS"


- hosts: all
  name: Install and setup apache2 server
  become: true
  tasks:

    - name: install apache2 on Ubuntu webserver
      apt: 
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: start apache2 service (Ubuntu)
      service: 
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Enable apache2 service (Ubuntu)
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Ubuntu"


    - name: Configure apache2 to listen on port 80 (Ubuntu)
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: 'Listen 80'
        line: 'Listen 80'
      notify: restart apache2
      when: ansible_distribution == "Ubuntu"

    - name: Setup Website 
      copy:
        src: ./default_html_file.html
        dest: /var/www/html/index.html
      when: ansible_distribution == "Ubuntu"

  handlers:
    - name: restart apache2
      service:
        name: apache
        state: restarted
        enabled: yes

